version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/buildSrc"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/sample-jdo"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/sample-jpa"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/sample-jpa-multiproject/common"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/sample-jpa-multiproject/domain"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"
