name: Java CI

on: [push]

jobs:
  build:
  
    name: Test on JDK ${{ matrix.jdk_version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        # JDK matrix version
        jdk_version: [ '1.8', '9', '10', '11', '12', '13', '14' ]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.jdk_version }}
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.jdk_version }}
    - name: Build with Gradle
      run: cd buildSrc && ../gradlew build check jacocoTestReport --stacktrace
